### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by Arenas17** [tytannial/H3FontExtension#2]
<img width="485" alt="image" src="https://github.com/tytannial/H3FontExtension/assets/169116164/03c83e25-0fbd-4045-bb40-3c3657c5efa5">
大佬，这个扩展怎么使用呀，能兼容最新的HOMM3 HOTA版本吗

**Comment by tytannial** [comment]
编译以后作为模块挂载，HDMOD挂载模块的方式请参考下他们的文档，支持大部分基于SOD3.2的exe，但对ERA的兼容很差。

**Comment by Arenas17** [comment]
请问如何编译，如何挂载呢，找不到参考文档，麻烦大佬教学下，小白懵逼中，感谢！发自我的手机-------- 原始邮件 --------发件人： Tytannial ***@***.***>日期： 2024年5月7日周二 11:03收件人： tytannial/H3FontExtension ***@***.***>抄送： Arenas17 ***@***.***>, Author ***@***.***>主    题： Re: [tytannial/H3FontExtension] 如何使用 (Issue #2)
编译以后作为模块挂载，HDMOD挂载模块的方式请参考下他们的文档，支持大部分基于SOD3.2的exe，但对ERA的兼容很差。
